// Vercel serverless function: /api/generate-image
// Uses Google's Imagen 3 model for image generation

const IMAGE_MODEL = "imagen-3.0-generate-002";

export default async function handler(req, res) {
  // CORS Headers
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");

  if (req.method === "OPTIONS") {
    return res.status(200).end();
  }

  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  try {
    const { prompt } = req.body;

    if (!prompt || typeof prompt !== "string") {
      return res.status(400).json({ error: "prompt is required" });
    }

    // Imagen 3 REST Endpoint
    const url = `https://generativelanguage.googleapis.com/v1beta/models/${IMAGE_MODEL}:predict?key=${process.env.GEMINI_API_KEY}`;

    const response = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        instances: [{ prompt: prompt }],
        parameters: {
          sampleCount: 1,
          aspectRatio: "1:1", // Options: "1:1", "3:4", "4:3", "9:16", "16:9"
          outputOptions: { mimeType: "image/jpeg" }
        },
      }),
    });

    if (!response.ok) {
      const errText = await response.text();
      return res.status(response.status).json({ error: errText });
    }

    const data = await response.json();
    const generatedImage = data?.predictions?.[0];

    if (!generatedImage || !generatedImage.bytesBase64Encoded) {
      return res.status(500).json({ error: "No image generated by the model" });
    }

    // Return image data to front-end
    return res.status(200).json({
      mimeType: generatedImage.mimeType || "image/jpeg",
      data: generatedImage.bytesBase64Encoded, // base64 string
    });
  } catch (err) {
    console.error("Image generation error:", err);
    return res.status(500).json({ error: "Server error" });
  }
}
